package sizelint

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var testLimits = Limits{MaxFileLines: 199, MaxFunctionLines: 50}

func functionFixture(signature string, lines int) string {
	return "package fixture\n\n" + signature + " {\n" + strings.Repeat("\t// Counted comment.\n", lines-2) + "}\n"
}

func checkFixture(t *testing.T, name, source string) []Diagnostic {
	t.Helper()
	diagnostics, err := CheckFile(name, []byte(source), testLimits)
	if err != nil {
		t.Fatal(err)
	}
	return diagnostics
}

func TestFunctionBoundary(t *testing.T) {
	for _, signature := range []string{"func example()", "func (r receiver) example()", "var example = func()"} {
		for _, lines := range []int{50, 51} {
			t.Run(fmt.Sprintf("%s/%d", signature, lines), func(t *testing.T) {
				source := functionFixture(signature, lines)
				diagnostics := checkFixture(t, "fixture.go", source)
				want := 0
				if lines > 50 {
					want = 1
				}

				if len(diagnostics) != want {
					t.Fatalf("got %v, want %d diagnostics", diagnostics, want)
				}

				if want == 1 && diagnostics[0].Rule != "max-lines-per-function" {
					t.Fatalf("unexpected rule: %v", diagnostics)
				}
			})
		}
	}
}

func TestFunctionCountsBlankLines(t *testing.T) {
	source := "package fixture\n\nfunc example() {\n" + strings.Repeat("\n\t// Comment.\n", 24) + "}\n"
	diagnostics := checkFixture(t, "fixture.go", source)
	if len(diagnostics) != 0 {
		t.Fatalf("exactly 50 lines: %v", diagnostics)
	}

	source = strings.Replace(source, "}\n", "\n}\n", 1)
	if diagnostics = checkFixture(t, "fixture.go", source); len(diagnostics) != 1 {
		t.Fatalf("51 lines including whitespace: %v", diagnostics)
	}
}

func TestFileBoundary(t *testing.T) {
	for _, lines := range []int{199, 200} {
		for _, ending := range []string{"", "\n"} {
			source := "package fixture\n" + strings.Repeat("// Comment.\n\n", 98) + "// Last comment.\n// Last line."
			if lines == 200 {
				source += "\n// Too long."
			}

			all := checkFixture(t, "fixture.go", source+ending)
			var diagnostics []Diagnostic

			for _, diagnostic := range all {
				if diagnostic.Rule != "gofmt" {
					diagnostics = append(diagnostics, diagnostic)
				}
			}

			want := lines - 199
			if len(diagnostics) != want {
				t.Fatalf("%d lines, ending %q: %v", lines, ending, diagnostics)
			}

			if want == 1 && diagnostics[0].Rule != "max-lines" {
				t.Fatalf("unexpected rule: %v", diagnostics)
			}
		}
	}
}

func TestNestedAndImmediatelyInvokedFunctions(t *testing.T) {
	body := strings.Repeat("\t\t// Comment.\n", 49)

	for _, source := range []string{
		"package fixture\n\nfunc outer() {\n\tfunc() {\n" + body + "\t}()\n}\n",
		"package fixture\n\nvar _ = func() {\n" + body + "}()\n",
	} {
		diagnostics := checkFixture(t, "fixture.go", source)
		if len(diagnostics) == 0 {
			t.Fatal("long closure was not rejected")
		}
	}
}

func TestExclusionsAndFormatting(t *testing.T) {
	long := functionFixture("func example()", 51)

	for _, fixture := range []struct{ name, source string }{
		{"fixture_test.go", long},
		{"generated.go", "// Code generated by fixture. DO NOT EDIT.\n\n" + long},
	} {
		if diagnostics := checkFixture(t, fixture.name, fixture.source); len(diagnostics) != 0 {
			t.Fatalf("excluded fixture: %v", diagnostics)
		}
	}

	for _, name := range []string{"fixture.go", "fixture_test.go"} {
		diagnostics := checkFixture(t, name, "package fixture\nfunc example(){ }\n")
		if len(diagnostics) != 1 || diagnostics[0].Rule != "gofmt" {
			t.Fatalf("formatting not enforced for %s: %v", name, diagnostics)
		}
	}
}

func TestParseErrorsAndPlatformFiles(t *testing.T) {
	if _, err := CheckFile("broken.go", []byte("package fixture\nfunc"), testLimits); err == nil {
		t.Fatal("expected parse failure")
	}

	root := t.TempDir()

	for _, name := range []string{"native_linux.go", "native_darwin.go"} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(functionFixture("func example()", 51)), 0600); err != nil {
			t.Fatal(err)
		}
	}

	if err := os.Mkdir(filepath.Join(root, "vendor"), 0700); err != nil {
		t.Fatal(err)
	}

	if err := os.WriteFile(filepath.Join(root, "vendor", "broken.go"), []byte("invalid"), 0600); err != nil {
		t.Fatal(err)
	}

	diagnostics, err := CheckTree(root, testLimits)
	if err != nil || len(diagnostics) != 2 {
		t.Fatalf("all platforms must be checked: %v, %v", diagnostics, err)
	}
}
