// Code generated by scripts/gen-walk-skip.sh; DO NOT EDIT.

package workspace

var skipDirs = map[string]struct{}{
	".git": {},
	"node_modules": {},
	"vendor": {},
	".venv": {},
	"__pycache__": {},
	".next": {},
	"dist": {},
	"build": {},
	"target": {},
	".gradle": {},
	".idea": {},
	".terraform": {},
}

// SkipDir names directories excluded from tree walks, aligned with cberg_walk_skip_dir.
func SkipDir(name string) bool {
	_, ok := skipDirs[name]
	return ok
}
