#!/usr/bin/env bash
# Generate walk skip-dir tables for C (core) and Go (daemon) from configs/walk_skip_dirs.txt.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/configs/walk_skip_dirs.txt"
C_OUT="$ROOT/core/src/common/walk_skip_dirs_gen.inc"
GO_OUT="$ROOT/daemon/internal/workspace/skip_gen.go"

if [[ ! -f "$SRC" ]]; then
  echo "missing $SRC" >&2
  exit 1
fi

mapfile -t DIRS < <(grep -v '^[[:space:]]*$' "$SRC" | grep -v '^[[:space:]]*#')

{
  echo "/* Generated by scripts/gen-walk-skip.sh — do not edit. */"
  echo "static const char *const cberg_walk_skip_dirs[] = {"
  for d in "${DIRS[@]}"; do
    printf '    "%s",\n' "$d"
  done
  echo "};"
} >"$C_OUT"

{
  echo "// Code generated by scripts/gen-walk-skip.sh; DO NOT EDIT."
  echo
  echo "package workspace"
  echo
  echo "var skipDirs = map[string]struct{}{"
  for d in "${DIRS[@]}"; do
    printf '\t"%s": {},\n' "$d"
  done
  echo "}"
  echo
  echo "// SkipDir names directories excluded from tree walks, aligned with cberg_walk_skip_dir."
  echo "func SkipDir(name string) bool {"
  cat <<'EOF'
	_, ok := skipDirs[name]
	return ok
EOF
  echo "}"
} >"$GO_OUT"

echo "wrote $C_OUT"
echo "wrote $GO_OUT"
